CREATE USER 'xframe' IDENTIFIED BY 'xframe'  
DEFAULT TABLESPACE 'TEMP'
TEMPORARY TABLESPACE 'TEMP';

ALTER USER 'xframe' DEFAULT ROLE 'DBA','CONNECT','RESOURCE';




--CREATE TABLE USERS(
--	USER_ID VARCHAR2(255) PRIMARY KEY,
--	USER_PWD VARCHAR2(100) NOT NULL,
--	USER_NAME VARCHAR2(100)
--);

-- 회원추가
--INSERT INTO USERS(USER_ID, USER_PWD, USER_NAME) VALUES ('a', 'a', '홍길동')
--------------------------------------------------------------------
-- 조회용 emp_info 테이블 생성
CREATE TABLE EMP_INFO(
	EMP_NO VARCHAR2(6) PRIMARY KEY,
	EMP_NAME VARCHAR2(20),
	EMP_AGE NUMBER(3),
	DEPT_CODE VARCHAR2(2),
	TITLE_CODE VARCHAR2(2),
	MAIL_ADDR VARCHAR2(100)
);

-- 조회용 emp_info 테이블 데이터 삽입
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100111', '김우섭', '49', '01', '05', 'wskim@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100112', '곽경환', '42', '02', '04', 'khkwan@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100115', '전시교', '50', '03', '05', 'skjeon@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100117', '김종인', '47', '04', '04', 'jikim@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100118', '유동균', '40', '05', '03', 'dkyou@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100124', '임기조', '35', '01', '02', 'kjlim@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100133', '김용진', '31', '02', '01', 'yjkim@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100212', '김용상', '36', '03', '02', 'yskim@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100215', '김용완', '54', '04', '05', 'ywkim@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100218', '김지태', '33', '05', '02', 'jtkim@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100221', '홍성일', '50', '01', '05', 'sihong@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100223', '김경환', '43', '02', '04', 'kyh@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100226', '정학길', '25', '03', '01', 'hkjung@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100312', '유승한', '29', '04', '01', 'shyou@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100319', '방인홍', '36', '05', '03', 'ihbang@gmail.com');
INSERT INTO EMP_INFO(EMP_NO, EMP_NAME, EMP_AGE, DEPT_CODE, TITLE_CODE, MAIL_ADDR) VALUES ('100325', '김종욱', '37', '01', '03', 'jwkim@gmail.com');

-- 테이블 삭제
--DROP TABLE EMP_INFO;

-- 테이블 검색
--SELECT * FROM EMP_INFO

-- 커밋
commit;